# =====================================================================
# app.R  -- Upload-based NFI Enquiries Dashboard (FINAL WORKING VERSION)
# =====================================================================

library(shiny)
library(shinydashboard)
library(DT)
library(dplyr)
library(stringr)
library(lubridate)
library(plotly)
library(reactable)
library(htmltools)
library(tidyr)
library(shinycssloaders)
library(shinyjs)

# =====================================================================
# UI SECTIONS
# =====================================================================

upload_gate_ui <- fluidPage(
  tags$br(), tags$br(),
  fluidRow(
    column(
      width = 6, offset = 3,
      box(
        width = NULL, title = "Upload NFI Dashboard Export File",
        status = "primary", solidHeader = TRUE,
        fileInput("upload_data", "Upload .rds file generated by the export script",
                  accept = ".rds"),
        tags$p("This dashboard requires an export file generated by the local NFI export script."),
        tags$p("Only users with access to the network directory can generate this file.")
      )
    )
  )
)

# -------------------- Main Dashboard UI --------------------

dashboard_ui <- dashboardPage(
  dashboardHeader(title = "NFI Enquiries Dashboard"),
  dashboardSidebar(
    width = 300,
    sidebarMenu(
      id = "tabs",
      menuItem("Overview", tabName = "overview", icon = icon("table")),
      menuItem("Detail",   tabName = "detail", icon = icon("file-alt"))
    ),
    hr(),
    tags$h4("Filters"),
    textInput("search_text", "Search title / notes", placeholder = "Type to search..."),
    sliderInput("age_filter", "Age (days)", min = 0, max = 180, value = c(0, 180)),
    hr(),
    helpText("Upload-based dashboard — no filesystem access required.")
  ),
  dashboardBody(
    tags$head(tags$link(rel="stylesheet", type="text/css", href="style.css")),
    tabItems(
      # OVERVIEW TAB ----------------------------------------------------
      tabItem(
        tabName = "overview",
        fluidRow(
          valueBoxOutput("kpi_total", width = 3),
          valueBoxOutput("kpi_overdue", width = 3),
          valueBoxOutput("kpi_avg_age", width = 3),
          valueBoxOutput("kpi_last_refreshed", width = 3)
        ),
        fluidRow(
          box(title = "Open Requests", width = 12, status = "primary",
              solidHeader = TRUE, DTOutput("requests_table") %>% withSpinner())
        ),
        fluidRow(
          box(title = "Chargeable (Y/N)", width = 4, status = "info",
              solidHeader = TRUE, plotlyOutput("chargeable_plot") %>% withSpinner()),
          box(title = "Status Distribution", width = 4, status = "info",
              solidHeader = TRUE, plotlyOutput("statusid_plot") %>% withSpinner()),
          box(title = "Requests by Owner", width = 4, status = "info",
              solidHeader = TRUE, plotlyOutput("owner_plot") %>% withSpinner()),
          box(title = "Organisation Distribution", width = 12, status = "info",
              solidHeader = TRUE, plotlyOutput("organisation_plot") %>% withSpinner())
        )
      ),
      
      # DETAIL TAB ------------------------------------------------------
      tabItem(
        tabName = "detail",
        fluidRow(
          box(
            title = "Selected Request",
            width = 4, status = "primary", solidHeader = TRUE,
            uiOutput("detail_meta")
          ),
          box(
            title = "ReadMe Timeline",
            width = 8, status = "primary", solidHeader = TRUE,
            reactableOutput("timeline_reactable")
          )
        )
      )
    )
  ),
  skin = "blue"
)

# =====================================================================
# SERVER
# =====================================================================

server <- function(input, output, session) {
  
  # -------------------------------------------------------------------
  # 1. Upload Gate
  # -------------------------------------------------------------------
  
  uploaded_data <- reactiveVal(NULL)
  
  observeEvent(input$upload_data, {
    req(input$upload_data)
    data <- readRDS(input$upload_data$datapath)
    uploaded_data(data)
    
    showModal(modalDialog(
      title = "Data loaded!",
      "The NFI export file has been successfully loaded.",
      easyClose = TRUE
    ))
  })
  
  # Show dashboard after upload
  observeEvent(uploaded_data(), {
    hide("upload_section")
    show("dashboard_section")
  })
  
  # -------------------------------------------------------------------
  # 2. Auto-Navigation (this now works because dashboard exists on load)
  # -------------------------------------------------------------------
  
  observeEvent(input$requests_table_rows_selected, {
    updateTabItems(session, "tabs", "detail")
  })
  
  # -------------------------------------------------------------------
  # 3. Loaded data access
  # -------------------------------------------------------------------
  
  requests <- reactive({
    req(uploaded_data())
    uploaded_data()$df
  })
  
  timeline_cache <- reactive({
    req(uploaded_data())
    uploaded_data()$timeline_cache
  })
  
  header_meta_df <- reactive({
    req(uploaded_data())
    uploaded_data()$header_meta
  })
  
  # -------------------------------------------------------------------
  # 4. Filtering Logic
  # -------------------------------------------------------------------
  
  add_buckets <- function(df) {
    df %>% mutate(
      age_bucket = case_when(
        age_days < 30 ~ "<30d",
        age_days < 60 ~ "30–59d",
        age_days < 90 ~ "60–89d",
        TRUE ~ "90d+"
      )
    )
  }
  
  filtered <- reactive({
    df <- requests()
    req(nrow(df) > 0)
    
    df <- add_buckets(df)
    df <- df %>%
      filter(is.na(age_days) | between(age_days, input$age_filter[1], input$age_filter[2]))
    
    if (isTruthy(input$search_text)) {
      s <- tolower(input$search_text)
      df <- df %>%
        filter(grepl(s, tolower(title)) | grepl(s, tolower(last_note)))
    }
    
    df
  })
  
  # -------------------------------------------------------------------
  # 5. Overview Table
  # -------------------------------------------------------------------
  
  table_df <- reactive({
    df <- filtered()
    meta <- header_meta_df()
    
    df2 <- df %>%
      left_join(meta, by = "path") %>%
      mutate(
        StatusID = recode(
          as.character(StatusID),
          "1"="waiting on client",
          "2"="work in progress",
          "3"="internal meeting planned",
          "4"="client review/completed",
          .default="(unknown)"
        )
      ) %>%
      select(
        code, user, title,
        Owner = `Owner (initials)`,
        Status = StatusID,
        Chargeable = `Chargeable (Y/N)`,
        Organisation,
        JobCode = `Job Code`,
        age_days,
        last_update,
        last_note,
        path
      )
    
    df2
  })
  
  output$requests_table <- renderDT({
    df <- table_df()
    datatable(
      df %>% select(-path),
      filter = "top",
      rownames = FALSE,
      selection = "single",
      options = list(pageLength = 15, scrollX = TRUE)
    )
  })
  
  selected_request <- reactive({
    s <- input$requests_table_rows_selected
    df <- table_df()
    if (length(s) == 0) return(NULL)
    df[s,]
  })
  
  # -------------------------------------------------------------------
  # 6. KPIs
  # -------------------------------------------------------------------
  
  output$kpi_total <- renderValueBox({
    valueBox(nrow(filtered()), "Open Requests", icon = icon("inbox"), color = "aqua")
  })
  
  output$kpi_overdue <- renderValueBox({
    valueBox(nrow(filtered() %>% filter(age_days >= 90)),
             "90d+ Overdue", icon = icon("hourglass-end"), color = "red")
  })
  
  output$kpi_avg_age <- renderValueBox({
    df <- filtered()
    avg <- ifelse(nrow(df) == 0, 0, round(mean(df$age_days, na.rm = TRUE), 1))
    valueBox(avg, "Average Age (days)", icon = icon("calendar-day"), color = "yellow")
  })
  
  output$kpi_last_refreshed <- renderValueBox({
    valueBox(format(Sys.time(), "%Y-%m-%d %H:%M:%S"),
             "Data Load Time", icon = icon("sync"), color = "green")
  })
  
  # -------------------------------------------------------------------
  # 7. Metadata Plots
  # -------------------------------------------------------------------
  
  meta_df2 <- reactive({
    header_meta_df()
  })
  
  # Chargeable
  output$chargeable_plot <- renderPlotly({
    m <- meta_df2()
    d <- m %>% count(`Chargeable (Y/N)`) %>%
      filter(`Chargeable (Y/N)` %in% c("Y","N"))
    
    plot_ly(
      d,
      labels = ~`Chargeable (Y/N)`,
      values = ~n,
      type = "pie",
      textinfo = "label+percent",
      insidetextorientation = "radial",
      marker = list(colors = c("#4CAF50", "#F44336"))
    )
  })
  
  # Organisation
  output$organisation_plot <- renderPlotly({
    m <- meta_df2()
    d <- m %>%
      filter(!is.na(Organisation), Organisation != "", Organisation != "0") %>%
      count(Organisation)
    
    plot_ly(d, x=~Organisation, y=~n, type="bar")
  })
  
  # StatusID
  output$statusid_plot <- renderPlotly({
    m <- meta_df2()
    
    d <- m %>%
      mutate(StatusID = recode(
        as.character(StatusID),
        "1"="waiting on client",
        "2"="work in progress",
        "3"="internal meeting planned",
        "4"="client review/completed",
        .default="(unknown)"
      )) %>%
      filter(StatusID != "(unknown)") %>%
      count(StatusID)
    
    plot_ly(d, x=~StatusID, y=~n, type="bar")
  })
  
  # Owner
  output$owner_plot <- renderPlotly({
    d <- meta_df2() %>% count(`Owner (initials)`)
    plot_ly(d, x=~`Owner (initials)`, y=~n, type="bar")
  })
  
  # -------------------------------------------------------------------
  # 8. Detail View
  # -------------------------------------------------------------------
  
  output$detail_meta <- renderUI({
    req <- selected_request()
    if (is.null(req)) return(NULL)
    req <- as.list(req)
    
    meta <- header_meta_df()
    h <- meta %>% filter(path == req$path)
    
    owner       <- h$`Owner (initials)` %||% "(None)"
    chargeable  <- h$`Chargeable (Y/N)` %||% "(None)"
    org         <- h$Organisation %||% "(None)"
    timespent   <- h$`Time Spent (number counting days)` %||% "(None)"
    statusid    <- h$StatusID %||% "(None)"
    
    wellPanel(
      strong("Code:"), req$code, br(),
      strong("User:"), req$user, br(),
      strong("Title:"), req$title, br(),
      hr(),
      strong("Owner:"), owner, br(),
      strong("Chargeable:"), chargeable, br(),
      strong("Organisation:"), org, br(),
      strong("Time Spent (days):"), timespent, br(),
      strong("StatusID:"), statusid, br(),
      hr(),
      strong("Age (days):"), req$age_days, br(),
      strong("Last update:"), req$last_update, br(),
      strong("Last note:"), req$last_note
    )
  })
  
  output$timeline_reactable <- renderReactable({
    req <- selected_request()
    if (is.null(req)) return(NULL)
    
    tl_obj <- timeline_cache()[[req$path]]
    tl <- tl_obj$timeline
    
    if (is.null(tl) || nrow(tl)==0)
      return(reactable(data.frame(Message="No timeline entries found")))
    
    reactable(
      tl,
      columns=list(
        date = colDef(name="Date", width=120),
        text = colDef(show=FALSE)
      ),
      striped=TRUE, highlight=TRUE, pagination=TRUE,
      defaultPageSize=10,
      details=function(i){
        htmltools::div(
          style="background-color:#f8f9fa; padding:12px; border-left:3px solid #007bff;
                 white-space:pre-wrap; font-family:Consolas;",
          tl$text[i]
        )
      }
    )
  })
  
}

# =====================================================================
# RUN APP (PRE-RENDERED DASHBOARD + UPLOAD GATE)
# =====================================================================

ui <- fluidPage(
  useShinyjs(),
  
  # Upload section (shown first)
  div(id = "upload_section",
      upload_gate_ui
  ),
  
  # Dashboard section (hidden until upload)
  hidden(
    div(id = "dashboard_section",
        dashboard_ui
    )
  )
)

shinyApp(ui = ui, server = server)
