# =====================================================================
# app.R  -- Enquiries Dashboard (Posit-safe, no folder button)
# =====================================================================

library(shiny)
library(shinydashboard)
library(DT)
library(dplyr)
library(stringr)
library(lubridate)
library(plotly)
library(reactable)
library(htmltools)
library(tidyr)
library(shinycssloaders)
library(shinyjs)

# =====================================================================
# FOREST RESEARCH BRANDING CSS
# =====================================================================

fr_branding_css <- tags$head(
  tags$style(HTML("

    :root {
      --fr-purple: #6E177E;
      --fr-purple-dark: #4E0F59;
      --fr-purple-light: #A884B2;
      --fr-bg-light: #FAF9FC;
      --fr-bg-panel: #FFFFFF;
      --fr-border: #DDDDE2;
      --fr-text: #2A2A2A;
    }

    body {
      background-color: var(--fr-bg-light) !important;
      color: var(--fr-text);
      font-family: 'Segoe UI', sans-serif;
    }

    .skin-black .main-header .navbar,
    .skin-black .main-header .logo {
      background-color: var(--fr-purple) !important;
      height: 60px !important;
      line-height: 60px !important;
      padding-left: 20px !important;
      border: none !important;
      color: white !important;
      font-weight: 600 !important;
      font-size: 22px !important;
      text-shadow: 0px 1px 2px rgba(0,0,0,0.25);
    }

    .fr-header-logo {
      position: absolute;
      right: 20px;
      top: 5px;
      height: 50px;
    }

    /* Remove sidebar toggle entirely */
    .skin-black .main-header .navbar .sidebar-toggle,
    .sidebar-toggle {
      display: none !important;
      visibility: hidden !important;
    }

    body.sidebar-collapse .main-sidebar {
      margin-left: 0 !important;
    }
    body.sidebar-collapse .content-wrapper {
      margin-left: 300px !important;
    }

    .content-wrapper,
    .right-side {
      margin-top: 0 !important;
      background-color: var(--fr-bg-light) !important;
    }

    .main-sidebar {
      margin-top: 60px !important;
      background-color: white !important;
      border-right: 1px solid var(--fr-border);
      width: 300px !important;
    }

    .sidebar-menu > li > a {
      color: var(--fr-text) !important;
      padding: 12px 20px !important;
      font-size: 15px !important;
      font-weight: 500 !important;
    }

    .sidebar-menu > li.active > a,
    .sidebar-menu > li:hover > a {
      background-color: var(--fr-purple-light) !important;
      color: white !important;
    }

    .sidebar-menu i { color: var(--fr-purple) !important; }

    .box {
      background-color: var(--fr-bg-panel) !important;
      border-radius: 10px !important;
      border: 1px solid var(--fr-border) !important;
      box-shadow: 0 2px 6px rgba(0,0,0,0.06) !important;
    }

    .box-header {
      background-color: var(--fr-purple) !important;
      color: white !important;
      font-weight: 600 !important;
      border-radius: 10px 10px 0 0 !important;
      border-bottom: 1px solid var(--fr-border) !important;
    }

    .form-control {
      border-radius: 6px !important;
      border: 1px solid var(--fr-border) !important;
    }

    .btn-default {
      background-color: var(--fr-purple) !important;
      color: white !important;
      border-radius: 6px !important;
      border: none !important;
    }

    .btn-default:hover {
      background-color: var(--fr-purple-dark) !important;
    }

  "))
)

# =====================================================================
# UPLOAD GATE — CLEAN VERSION (NO folder button)
# =====================================================================

upload_gate_ui <- div(
  class = "upload-bg",
  tags$img(src = "FR_RGB.jpg", class = "fr-logo-top-right"),
  fluidRow(
    column(
      width = 6, offset = 3,
      box(
        width = NULL,
        title = "Upload NFI Dashboard Export File",
        status = "primary",
        solidHeader = TRUE,
        class = "upload-card",
        
        fileInput(
          "upload_data",
          "Choose the exported .rds file",
          accept = ".rds",
          width = "100%"
        ),
        
        tags$p("Please upload the latest nfi_dashboard_export.rds file generated by the export script.")
      )
    )
  )
)

# =====================================================================
# DASHBOARD UI
# =====================================================================

dashboard_ui <- dashboardPage(
  dashboardHeader(
    title = tagList(
      span("Enquiries Dashboard"),
      tags$img(src = "FR_RGB.jpg", class = "fr-header-logo")
    )
  ),
  
  dashboardSidebar(
    width = 300,
    sidebarMenu(
      id = "tabs",
      menuItem("Overview", tabName = "overview", icon = icon("table")),
      menuItem("Detail",   tabName = "detail",  icon = icon("file-alt"))
    ),
    hr(),
    tags$h4("Filters"),
    textInput("search_text", "Search title / notes"),
    sliderInput("age_filter", "Age (days)", min = 0, max = 180, value = c(0,180)),
    hr()
  ),
  
  dashboardBody(
    tabItems(
      
      tabItem(
        tabName = "overview",
        fluidRow(
          valueBoxOutput("kpi_total", width = 3),
          valueBoxOutput("kpi_overdue", width = 3),
          valueBoxOutput("kpi_avg_age", width = 3),
          valueBoxOutput("kpi_last_refreshed", width = 3)
        ),
        fluidRow(
          box(title="Open Requests", width=12, status="primary",
              solidHeader=TRUE, DTOutput("requests_table") %>% withSpinner())
        ),
        fluidRow(
          box(title="Chargeable", width=4, status="info",
              plotlyOutput("chargeable_plot") %>% withSpinner()),
          box(title="Status Distribution", width=4, status="info",
              plotlyOutput("statusid_plot") %>% withSpinner()),
          box(title="Requests by Owner", width=4, status="info",
              plotlyOutput("owner_plot") %>% withSpinner()),
          box(title="Organisation Distribution", width=12, status="info",
              plotlyOutput("organisation_plot") %>% withSpinner())
        )
      ),
      
      tabItem(
        tabName = "detail",
        fluidRow(
          box(title="Selected Request", width=4, status="primary", uiOutput("detail_meta")),
          box(title="ReadMe Timeline", width=8, status="primary", reactableOutput("timeline_reactable"))
        )
      )
    )
  ),
  
  skin = "black"
)

# =====================================================================
# SERVER
# =====================================================================

server <- function(input, output, session) {
  
  uploaded_data <- reactiveVal(NULL)
  
  # Load uploaded file safely
  observeEvent(input$upload_data, {
    req(input$upload_data)
    uploaded_data(readRDS(input$upload_data$datapath))
  })
  
  # Reveal dashboard once file is uploaded
  observeEvent(uploaded_data(), {
    hide("upload_section")
    show("dashboard_section")
  })
  
  # ✅ Auto-switch to Detail tab after a row is clicked
  observeEvent(input$requests_table_rows_selected, {
    if (!is.null(uploaded_data())) {
      updateTabItems(session, "tabs", "detail")
    }
  })
  
  # Data accessors
  requests <- reactive(uploaded_data()$df)
  timeline_cache <- reactive(uploaded_data()$timeline_cache)
  header_meta_df <- reactive(uploaded_data()$header_meta)
  
  add_buckets <- function(df) {
    df %>% mutate(
      age_bucket = case_when(
        age_days < 30 ~ "<30d",
        age_days < 60 ~ "30–59d",
        age_days < 90 ~ "60–89d",
        TRUE ~ "90d+"
      )
    )
  }
  
  filtered <- reactive({
    df <- requests()
    req(nrow(df) > 0)
    
    df <- add_buckets(df)
    
    df <- df %>% filter(is.na(age_days) |
                          between(age_days, input$age_filter[1], input$age_filter[2]))
    
    if (isTruthy(input$search_text)) {
      s <- tolower(input$search_text)
      df <- df %>% filter(grepl(s, tolower(title)) | grepl(s, tolower(last_note)))
    }
    
    df
  })
  
  table_df <- reactive({
    df <- filtered()
    meta <- header_meta_df()
    
    df2 <- df %>%
      left_join(meta, by = "path") %>%
      mutate(
        StatusID = recode(
          as.character(StatusID),
          "1"="waiting on client",
          "2"="work in progress",
          "3"="internal meeting planned",
          "4"="client review/completed",
          .default="(unknown)"
        )
      ) %>%
      select(
        code, user, title,
        Owner = `Owner (initials)`,
        Status = StatusID,
        Chargeable = `Chargeable (Y/N)`,
        Organisation,
        JobCode = `Job Code`,
        age_days,
        last_update,
        last_note,
        path
      )
    
    df2
  })
  
  output$requests_table <- renderDT({
    df <- table_df()
    datatable(
      df %>% select(-path),
      filter = "top",
      rownames = FALSE,
      selection = "single",
      options = list(pageLength = 15, scrollX = TRUE)
    )
  })
  
  selected_request <- reactive({
    s <- input$requests_table_rows_selected
    df <- table_df()
    if (!length(s)) return(NULL)
    df[s,]
  })
  
  output$kpi_total <- renderValueBox({
    valueBox(nrow(filtered()), "Open Requests", icon = icon("inbox"), color = "purple")
  })
  
  output$kpi_overdue <- renderValueBox({
    valueBox(nrow(filtered() %>% filter(age_days >= 90)),
             "90d+ Overdue", icon = icon("hourglass-end"), color = "red")
  })
  
  output$kpi_avg_age <- renderValueBox({
    df <- filtered()
    avg <- ifelse(nrow(df)==0,0, round(mean(df$age_days, na.rm=TRUE),1))
    valueBox(avg, "Average Age (days)", icon = icon("calendar-day"), color = "purple")
  })
  
  output$kpi_last_refreshed <- renderValueBox({
    valueBox(format(Sys.time(), "%Y-%m-%d %H:%M:%S"),
             "Data Load Time", icon = icon("sync"), color = "green")
  })
  
  meta_df2 <- reactive(header_meta_df())
  
  output$chargeable_plot <- renderPlotly({
    m <- meta_df2()
    d <- m %>% count(`Chargeable (Y/N)`) %>% filter(`Chargeable (Y/N)` %in% c("Y","N"))
    plot_ly(d, labels=~`Chargeable (Y/N)`, values=~n, type="pie")
  })
  
  output$organisation_plot <- renderPlotly({
    m <- meta_df2()
    d <- m %>% filter(!is.na(Organisation), Organisation!="", Organisation!="0") %>% count(Organisation)
    plot_ly(d, x=~Organisation, y=~n, type="bar")
  })
  
  output$statusid_plot <- renderPlotly({
    m <- meta_df2()
    d <- m %>%
      mutate(StatusID = recode(as.character(StatusID),
                               "1"="waiting on client",
                               "2"="work in progress",
                               "3"="internal meeting planned",
                               "4"="client review/completed"
      )) %>%
      count(StatusID)
    
    plot_ly(d, x=~StatusID, y=~n, type="bar")
  })
  
  output$owner_plot <- renderPlotly({
    d <- meta_df2() %>% count(`Owner (initials)`)
    plot_ly(d, x=~`Owner (initials)`, y=~n, type="bar")
  })
  
  # DETAIL PANEL
  output$detail_meta <- renderUI({
    req <- selected_request()
    if (is.null(req)) return(NULL)
    req_list <- as.list(req)
    
    meta <- header_meta_df()
    h <- meta %>% filter(path == req_list$path)
    
    wellPanel(
      strong("Code:"), req_list$code, br(),
      strong("User:"), req_list$user, br(),
      strong("Title:"), req_list$title, br(),
      hr(),
      strong("Owner:"), h$`Owner (initials)` %||% "(None)", br(),
      strong("Chargeable:"), h$`Chargeable (Y/N)` %||% "(None)", br(),
      strong("Organisation:"), h$Organisation %||% "(None)", br(),
      strong("Time Spent:"), h$`Time Spent (number counting days)` %||% "(None)", br(),
      strong("StatusID:"), h$StatusID %||% "(None)", br(),
      hr(),
      strong("Age (days):"), req_list$age_days, br(),
      strong("Last update:"), req_list$last_update, br(),
      strong("Last note:"), req_list$last_note
    )
  })
  
  # TIMELINE PANEL
  output$timeline_reactable <- renderReactable({
    req <- selected_request()
    if (is.null(req)) return(NULL)
    
    tl <- timeline_cache()[[req$path]]$timeline
    
    if (is.null(tl) || nrow(tl) == 0)
      return(reactable(data.frame(Message = "No timeline entries found")))
    
    reactable(
      tl,
      columns = list(
        date = colDef(name = "Date", width = 120),
        text = colDef(show = FALSE)
      ),
      striped = TRUE,
      highlight = TRUE,
      pagination = TRUE,
      defaultPageSize = 1000,
      details = function(i) {
        htmltools::div(
          style = "background-color:#f8f9fa; padding:12px;
                   border-left:3px solid var(--fr-purple);
                   white-space:pre-wrap; font-family:Consolas;",
          tl$text[i]
        )
      },
      defaultExpanded = TRUE
    )
  })
}

# =====================================================================
# RUN APP
# =====================================================================

ui <- fluidPage(
  useShinyjs(),
  fr_branding_css,
  div(id = "upload_section", upload_gate_ui),
  hidden(div(id = "dashboard_section", dashboard_ui))
)

shinyApp(ui = ui, server = server)